### ISSUE TITLE
windows build结束之后缺少helper.exe

### ISSUE THREAD

**Issue by pt4300** [bincooo/chatgpt-adapter#127]
通过wsl build server.exe之后使用 ./bin/windows/server config.yaml 会报下述错误
2025-03-02 11:09:39 <chatgpt-adapter/core> common/exec.go:19 | [FATA] executable file not exists: bin/windows/helper.exe

**Comment by pt4300** [comment]
通过下载hel branch下的helper文件成功能在linux下运行了，但是windows还是不行。还有docker也有同样问题，必须在没有mount config.yaml的情况下先创建container然后通过手动复制黏贴helper文件到app/文件夹下才能正常运行

**Comment by pt4300** [comment]
如果作者有空更新一下这个问题的话就最好了，感谢

**Comment by Zhwt** [comment]
没太看懂原问题的意思, docker 启动可以手动复制 bin 目录到当前目录之后在运行命令里添加绑定:

```
docker run -p 8080:8080 -v ./config.yaml:/app/config.yaml -v ./bin:/app/bin ghcr.io/bincooo/chatgpt-adapter:latest
```

或者 docker compose 运行:

新建 `docker-compose.yml` 文件, 然后用 `docker compose up -d` 拉起服务:

```
version: '3.8'

services:
  chatgpt-adapter:
    image: ghcr.io/bincooo/chatgpt-adapter:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yaml
      - ./bin:/app/bin
```
