### ISSUE TITLE
3.0构建失败

### ISSUE THREAD

**Issue by normana234** [bincooo/chatgpt-adapter#78]
试了几个系统都是各种undefined报错
![error](https://github.com/user-attachments/assets/2e812545-c358-4856-ac88-5600431c1486)
然后，也用了下文档那边的helper.exe，报404
![error2](https://github.com/user-attachments/assets/49ca3883-08f3-493a-9d82-99d1da9c1fe5)

**Comment by bincooo** [comment]
已修，可参考 https://huggingface.co/spaces/wIK5Ez2o/DEMO/blob/main/Dockerfile 部署

**Comment by normana234** [comment]
@bincooo ok，更新后成功构建

**Comment by bincooo** [comment]
v1 转发？

这部分文档忘记写了
```yaml
custom-llm:
  - prefix: gitHub
    proxied: true
    reversal: https://models.inference.ai.azure.com
  - prefix: grok
    proxied: true
    reversal: https://api.x.ai/v1
```
`prefix` 前缀

`proxied` 是否使用代理

`reversal` 转发地址

例子： `github/gpt_4o` `grok/grok-beta`

**Comment by normana234** [comment]
@bincooo 不确定是不是一个意思(代码外行)，我的意思是在lmsys模型列表没及时更新，在官网看有什么新模型，加上lmsys/的前缀就能调用了，比如目前lmsys官网的gemini-exp-1206模型两个版本都没模型信息，2.x的模型填lmsys/gemini-exp-1206调用成功，3.0会报尚不支持此模型。
如果是这个功能，那reversal直接填lmsys官网地址吗？

**Comment by normana234** [comment]
@bincooo 
今天新构建的3.0。
lmsys后台500
![报错](https://github.com/user-attachments/assets/54965392-043b-43c7-89fb-96085e6df01c)
blackbox后台200，前台显示
【Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai and for API requests replace https://www.blackbox.ai with https://api.blackbox.ai】

留档的大概1个多星期前的3.0版本两者都正常。
测试时没换过网络，除了替换可执行文件外，其他的配置文件都相同。

另，上面提到的feat: 配置化模型列表 (#78)
目前还是报【model 'lmsys/gemini-2.0-flash-exp' is not not yet supported】。

**Comment by bincooo** [comment]
lmsys有些变化，你需要：
```yaml
lmsys:
  token: |
    {
      "gemini-2.0-flash-exp": [106, 156]
    }
  model:
    - gemini-2.0-flash-exp
```
