### ISSUE TITLE
help me to run using my you.com premium cookie on windows 10

### ISSUE THREAD

**Issue by bugbounted** [bincooo/chatgpt-adapter#98]
hi [bincooo](https://github.com/bincooo),
please help me to run using my you.com premium cookie on windows 10  ... I'm going your ways but getting multi error 
waiting for your accurate guideline for win 10
regards

**Comment by bincooo** [comment]
you can access `you.com` in chrome by logging in and clicking the F12 button, which will take you to `Developer Tools`.
you need to select the network panel, and then refresh the page, find the "https://you.com/api/instrumentation" requests, including a Cookie parameter, please double click copy it out:

<img width="620" alt="Image" src="https://github.com/user-attachments/assets/a301b009-a03c-455e-8a95-af67d9b5bc60" />

then configure in `config.yaml`:
```yaml
you:
  custom: false
  cookies:
    - 'uuid_guest=3db0e8c0-c6bf-494a-a034-bdb3e103cfb0; uuid_guest_backup=3db0exxx'
```

**Comment by bugbounted** [comment]
hello again, 
at the first special thanks for your special work ,
is it possible directly run it from bin builds without go build & run ?
& also tell me more about you helper exe 
finest regards

**Comment by bincooo** [comment]
1. you can download the Archive file named 'Archive.zip' in 'Releases'
2. you can deploy applications through docker
```shell
docker pull ghcr.io/bincooo/chatgpt-adapter:latest
```

**Comment by bugbounted** [comment]
special thanks bro , also tell me more about you helper.exe & flags 
regards

**Comment by bincooo** [comment]
'helper.exe' is an automatic subroutine that relies on the chrome browser to handle bot validation information.
the modules currently used in this subroutine are:

- you.com
- bing copilot
- coze

however, this is not required and can be used according to the situation.

if you have a model conversation fail with 403 error code, you can try to configure it:

- 1. download `helper` and put it in the directory. you can get and update it in the `hel` branch

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/1300da53-017a-4769-82d5-4c36743d0330" />

<img width="432" alt="Image" src="https://github.com/user-attachments/assets/c0f1b128-1ef0-4cb5-9f87-7c49073d99ef" />

- 2. open it in the configuration file `config.yaml`
```yaml
browser-less:
  enabled: true
  port: 8080
  #reversal: http://127.0.0.1:8080 # it can run alone
  disabled-gpu: true
  headless: new
```
