### ISSUE TITLE
add o3 mini & o3 mini (high effort) models as accepted custom models for you.com

### ISSUE THREAD

**Issue by bugbounted** [bincooo/chatgpt-adapter#99]
hello again [bincooo](https://github.com/bincooo),
add o3 mini & o3 mini (high effort) models as accepted custom models for you.com
waiting for your commit or branch 
regards

**Comment by bugbounted** [comment]
also models name in requests are :

streaming_mode=chat_custom_openai_o3_mini_high
streaming_mode=chat_custom_openai_o3_mini_medium

in cookies :

ai_model=openai_o3_mini_high
ai_model=openai_o3_mini_medium

regards

**Comment by bincooo** [comment]
add new models, you can do this:

```yaml
you:
  custom: false
  model:
    - openai_o3_mini_high
    - openai_o3_mini_medium
  cookies:
    - 'uuid_guest=3db0e8c0-c6bf-494a-a034-bdb3e103cfb0; uuid_gxxxxxx ....'
```
